discovery:
  enabled: false
  
gateway:
  certGenJob: false
  upgrade: false
  validation: false
  deployment:
    stats: false

gatewayProxies:
  gatewayProxyV2:
    stats: false
    gatewaySettings:
      customHttpsGateway:
        plugins:
          httpConnectionManagerSettings:
            useRemoteAddress: true
      customHttpGateway:
        plugins:
          httpConnectionManagerSettings:
            useRemoteAddress: true

gloo:
  deployment:
    stats: false

namespace:
  create: false

